language: java

jdk:
  - openjdk8

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script:
  - ./build.sh deps
  - ./build.sh npm
  - ./gradlew build test jacocoTestReport 

after_success:
  - ./gradlew alljacoco
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    rooms: blocko:LwABz6vDzniWNDuDgtYIeqrf
    on_success: change
    on_failure: always

